name: "DEV DEPLOY"

on:
    push:
        branches:
            - develop

permissions:
    id-token: write
    contents: read
                
jobs:
    terraform:
        uses: ./.github/workflows/terraform.yml
        with:
            environment: dev
            aws-assume-role-arn: "arn:aws:iam::921867984128:role/github-actions-mario-maciel-pipeline"
            aws-region: "sa-east-1"
            aws-statefile-s3-bucket: "mario-maciel-sa-east-1-terraform-statefile"
            aws-lock-dynamodb-table: "mario-maciel-sa-east-1-terraform-lock"
         
